### ISSUE TITLE
dlib 19.4 for Python 2.7

### ISSUE THREAD

**Issue by mrkaworu** [conda-forge/dlib-feedstock#10]
Are you planning to include support for Python 2.7? I saw through conda search that there is support for both Python 3.5 and 3.6 but for 2.7 ends in the 19.0 version of dlib.

**Comment by patricksnape** [comment]
On which Operating system?

**Comment by mrkaworu** [comment]
Windows! I´m trying to port a code from a Linux system already using version 19.4 on Python 2.7 and some of the libraries are not Python 3 compatible...

**Comment by patricksnape** [comment]
Unfortunately there will not be Windows builds for Python 2.7 due to the C++11 requirement in the later versions of dlib.
