### ISSUE TITLE
Import error for library

### ISSUE THREAD

**Issue by kevinlu1211** [conda-forge/dlib-feedstock#5]
I am getting this import error:
`ImportError: dlopen(/Users/kevinlu/miniconda3/envs/facial_recognition_2/lib/python3.5/site-packages/dlib.so, 2): Symbol not found: __ZN5boost6python7objects15function_objectERKNS1_11py_functionERKNSt3__14pairIPKNS0_6detail7keywordESA_EE
  Referenced from: /Users/kevinlu/miniconda3/envs/facial_recognition_2/lib/python3.5/site-packages/dlib.so
  Expected in: /Users/kevinlu/miniconda3/envs/facial_recognition_2/lib/python3.5/site-packages/../../libboost_python.dylib
 in /Users/kevinlu/miniconda3/envs/facial_recognition_2/lib/python3.5/site-packages/dlib.so`
 
Any ideas on how to fix this?

**Comment by patricksnape** [comment]
Looks like the wrong version of boost is being linked to?

**Comment by terencezl** [comment]
I had this after doing a clean installation with python3.5, opencv and dlib. The default cloud's boost was installed. Then I installed the conda-forge's version.

```
The following packages will be UPDATED:

    boost: 1.61.0-py35_0             --> 1.61.0-py35_2 conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    icu:   58.1-1        conda-forge --> 56.1-4        conda-forge
```

Everything is fine.
